[package]
name = "nettool"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.0"
walkdir = "2.3"
indicatif = "0.17"
humantime = "2.1"
pretty-bytes = "0.2"

[dev-dependencies]
assert_cmd = "1.0"
predicates = "1.0"

